export enum Configuration {
   PORT = "PORT",
   HOST = "HOST",
   USERNAME = "USERNAME",
   PASSWORD = "PASSWORD",
   DATABASE = "DATABASE",
   DATABASE_PORT = "DATABASE_PORT",
   DATABASE_NAME = "DATABASE_NAME",
   JWT_SECRET = 'JWT_SECRET',
}